Update README.md
Updating documentation to include building core which is required to run any of the examples.

Otherwise, you get:
Error: Cannot find module 'url-join'